version: "3"
services:
  brahman-app:
    container_name: brahman-app
    hostname: brahman-app
    image: brahman-app/sdk
    build: .
    volumes:
      - ~/src/brahman-app:/usr/src/brahman-app
    working_dir: /usr/src/brahman-app
    ports:
      - "9500:9500"

